name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - workshop-01
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and test
        run: |
          npm install-ci-test
      - name: Deploy 🚀
        run: |
          npm run deploy
